object Versions {
    const val buildGradleVersion = "7.1.3"
    const val kotlinGradlePluginVersion = "1.6.21"

    const val koinVersion = "3.1.6"
    const val navigationVersion = "2.4.2"
    const val lifecycleVersion = "2.4.1"
    const val lifecycleExtVersion = "2.2.0"
    const val retrofitVersion = "2.9.0"
    const val retrofitInterceptorVersion = "4.9.0"
    const val retrofitMoshiVersion = "1.8.0"
    const val roomVersion = "2.4.2"
    const val coroutinesVersion = "1.5.1"
    const val androidxCoreVersion = "1.7.0"
    const val appcompatVersion = "1.4.0"
    const val materialVersion = "1.4.0"
    const val constrainLayoutVersion = "2.1.2"
    const val recyclerViewVersion = "1.2.1"
    const val fragmentVersion = "1.4.0"
    const val cardViewVersion = "1.0.0"
    const val swipeRefreshVersion = "1.1.0"
    const val legacySupportVersion = "1.0.0"
    const val junitVersion = "4.13.2"
    const val junitExtVersion = "1.1.3"
    const val espressoCoreVersion = "3.4.0"
    const val glideVersion = "4.12.0"
    const val glideCompilerVersion = "4.12.0"
    const val timberVersion = "4.7.1"
    const val lottieVersion = "4.2.2"
    const val cameraXVersion = "1.1.0"
    const val mapsVersion = "18.0.0"
}